name: Build and Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Debug - Show current directory and files
        run: |
          echo "Current working directory:"
          pwd
          echo "Files:"
          ls -al
          echo "Exporting PYTHONPATH..."
          export PYTHONPATH=$(pwd)
          echo "PYTHONPATH=$PYTHONPATH"

      - name: Debug - Print Python sys.path
        run: |
          python -c "import sys; print('sys.path:', sys.path)"

      - name: Build package
        run: |
          export PYTHONPATH=$(pwd)
          python -m build --no-isolation

      - name: Upload dist files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          path: dist/

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine wheel

      - name: Download built package
        uses: actions/download-artifact@v4
        with:
          name: dist-artifacts
          path: dist/

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
